[package]
name = 'hy_spc_hpc'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.85'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'hy_spc_hpc'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '*'
faer = "0.19"
petgraph = "0.6"
dgcmatrix-faer-bridge = { git = "https://github.com/shinigami-777/dgcmatrix-faer-bridge" }

[profile.release]
lto = true
codegen-units = 1
