# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib hySpc.hpc, .registration = TRUE
NULL

#' Solve graph-based spatial smoothing: (I + alpha * L) x = b
#'
#' The pixel neighborhood graph is reconstructed in
#' Rust with `petgraph` from `width`/`height`/`neighbors` (no adjacency
#' matrix crosses the FFI boundary), the combinatorial Laplacian
#' `L = D - W` is assembled directly in CSC form, and the linear system
#' `(I + alpha * L) x = b` is solved band-by-band with an iterative
#' Krylov solver: Conjugate Gradient (`"cg"`, the default -- the
#' operator is symmetric positive-definite) or BiCGSTAB (`"bicgstab"`).
#'
#' @param data RMatrix of input spectra data.
#' @param width width of the image.
#' @param height height of the image.
#' @param alpha smoothing parameter.
#' @param neighbors connection type (4 or 8).
#' @param solver iterative method, `"cg"` or `"bicgstab"`.
#' @export
graph_smooth_rust <- function(data, width, height, alpha, neighbors, solver) .Call(wrap__graph_smooth_rust, data, width, height, alpha, neighbors, solver)

#' Compute row sums of an R dgCMatrix using the Rust faer bridge.
#'
#' Extract `p`, `i`, `x` slots of a `dgCMatrix` on the R side, transfer them through extendr, reconstruct a faer SparseColMat` via the `dgcmatrix-faer-bridge` crate,
#'  and return the row sums to R. This is the minimal round-trip that exercises the dgCMatrix -> faer FFI bridge end-to-end.
#' @noRd
dgc_row_sums_rust <- function(p, i, x, nrow, ncol) .Call(wrap__dgc_row_sums_rust, p, i, x, nrow, ncol)

#' Diagnostic helper to expose pixel graph connectivity stats to R
#' @noRd
pixel_graph_stats_rust <- function(width, height, neighbors) .Call(wrap__pixel_graph_stats_rust, width, height, neighbors)

#' Diagnostic helper to expose the combinatorial Laplacian L = D - W
#' @noRd
laplacian_matrix_rust <- function(width, height, neighbors) .Call(wrap__laplacian_matrix_rust, width, height, neighbors)

#' Dynamically set the number of worker threads used by the Rust HPC backend.
#'
#' Builds a dedicated Rayon thread pool with `n` threads. Subsequent parallel
#' operations (e.g. `graph_smooth_rust`) will execute on this pool.
#'
#' @param n integer number of worker threads (must be >= 1).
#' @export
set_hpc_threads_rust <- function(n) .Call(wrap__set_hpc_threads_rust, n)

#' Query the number of active worker threads in the Rust HPC backend.
#'
#' Returns the thread count of the active custom thread pool if configured,
#' or Rayon's global thread count.
#'
#' @export
get_hpc_threads_rust <- function() .Call(wrap__get_hpc_threads_rust)

# nolint end
